# Site settings
title: KEBIR MOUNDIR CHEMSEDDINE
description: Jekyll Theme Minimal Resume
baseurl: www.moundirchemseddine.ga # the subpath of your site, e.g. /blog
url:  www.moundirchemseddine.ga

# User settings
username: KEBIR MOUNDIR CHEMSEDDINE
user_description: I\'m a nomad Telecommunications Engineer, always searching for the next challenge,i like play CTF  ; no task is too scary nor too difficult . I'm one of the two guys behind all the security related stuff.
user_title: Telecommunications engineering | Pentester| Network security
email: mauriurraco@gmail.com
 #twitter_username: mondirkb
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
